on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]

name: Create RPM Release

jobs:
  call-rpmbuild-workflow:
    uses: fmidev/github-actions-workflows/.github/workflows/rpmbuild-workflow.yaml@main
    with:
      rpm_base_image: rockylinux/rockylinux:8
      rpm_spec_file: mos-tools.spec
      rpm_additional_repositories: "epel-release,https://download.fmi.fi/smartmet-open/rhel/8/x86_64/smartmet-open-release-latest-8.noarch.rpm,https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
      rpm_enable_repositories: powertools
      rpm_disable_modules: postgresql
      rpm_dnf_commands: "dnf config-manager --setopt='epel.exclude=eccodes*' --save"
      image_name: mos-tools
      image_test_command: mosse --help
    secrets:
      RPM_API_HOST: ${{ secrets.RPM_API_HOST }}
      RPM_API_USER: ${{ secrets.RPM_API_USER }}
      RPM_API_PASS: ${{ secrets.RPM_API_PASS }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
